/// Multi-language support for HostelCare
class AppLocalizations {
  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'app_name': 'HostelCare+',
      'login': 'Sign In',
      'register': 'Create Account',
      'email': 'Email',
      'password': 'Password',
      'name': 'Full Name',
      'submit_complaint': 'Submit Complaint',
      'my_complaints': 'My Complaints',
      'dashboard': 'Dashboard',
      'profile': 'Profile',
      'title': 'Title',
      'description': 'Description',
      'category': 'Category',
      'priority': 'Priority',
      'status': 'Status',
      'pending': 'Pending',
      'assigned': 'Assigned',
      'in_progress': 'In Progress',
      'resolved': 'Resolved',
      'closed': 'Closed',
      'electrical': 'Electrical',
      'water': 'Water',
      'internet': 'Internet',
      'cleaning': 'Cleaning',
      'furniture': 'Furniture',
      'security': 'Security',
      'low': 'Low',
      'medium': 'Medium',
      'high': 'High',
      'urgent': 'Urgent',
      'notifications': 'Notifications',
      'settings': 'Settings',
      'logout': 'Sign Out',
      'dark_mode': 'Dark Mode',
      'ai_assistant': 'AI Assistant',
      'scan_qr': 'Scan QR Code',
      'no_complaints': 'No complaints yet',
      'submit': 'Submit',
      'cancel': 'Cancel',
      'feedback': 'Feedback',
      'rate_resolution': 'Rate Resolution',
    },
    'hi': {
      'app_name': 'हॉस्टलकेयर',
      'login': 'साइन इन',
      'register': 'खाता बनाएं',
      'email': 'ईमेल',
      'password': 'पासवर्ड',
      'name': 'पूरा नाम',
      'submit_complaint': 'शिकायत दर्ज करें',
      'my_complaints': 'मेरी शिकायतें',
      'dashboard': 'डैशबोर्ड',
      'profile': 'प्रोफ़ाइल',
      'title': 'शीर्षक',
      'description': 'विवरण',
      'category': 'श्रेणी',
      'priority': 'प्राथमिकता',
      'status': 'स्थिति',
      'pending': 'लंबित',
      'assigned': 'आवंटित',
      'in_progress': 'प्रगति में',
      'resolved': 'हल किया',
      'closed': 'बंद',
      'electrical': 'विद्युत',
      'water': 'पानी',
      'internet': 'इंटरनेट',
      'cleaning': 'सफाई',
      'notifications': 'सूचनाएं',
      'logout': 'लॉग आउट',
      'dark_mode': 'डार्क मोड',
      'ai_assistant': 'AI सहायक',
      'scan_qr': 'QR स्कैन करें',
      'submit': 'सबमिट',
      'cancel': 'रद्द करें',
      'feedback': 'प्रतिक्रिया',
    },
    'ta': {
      'app_name': 'HostelCare+',
      'login': 'உள்நுழைக',
      'register': 'கணக்கை உருவாக்கு',
      'submit_complaint': 'புகார் அளிக்கவும்',
      'my_complaints': 'எனது புகார்கள்',
      'dashboard': 'டாஷ்போர்டு',
      'profile': 'சுயவிவரம்',
      'notifications': 'அறிவிப்புகள்',
      'logout': 'வெளியேறு',
    },
    'te': {
      'app_name': 'HostelCare+',
      'login': 'సైన్ ఇన్',
      'register': 'ఖాతాను సృష్టించండి',
      'submit_complaint': 'ఫిర్యాదు సమర్పించండి',
      'my_complaints': 'నా ఫిర్యాదులు',
      'dashboard': 'డ్యాష్‌బోర్డ్',
      'notifications': 'నోటిఫికేషన్లు',
      'logout': 'లాగ్ అవుట్',
    },
  };

  static String translate(String key, {String locale = 'en'}) {
    return _translations[locale]?[key] ?? _translations['en']?[key] ?? key;
  }

  static List<String> get supportedLocales => _translations.keys.toList();

  static String getLocaleName(String code) {
    const names = {'en': 'English', 'hi': 'हिंदी', 'ta': 'தமிழ்', 'te': 'తెలుగు', 'kn': 'ಕನ್ನಡ', 'ml': 'മലയാളം'};
    return names[code] ?? code;
  }
}
